# Generated by Django 3.0.8 on 2021-06-23 14:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stepcell', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='YoutubeUpdate',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('embed_link', models.CharField(help_text='embed link from youtube, only src url will be taken', max_length=1000, null=True)),
                ('title', models.CharField(help_text='title', max_length=300, null=True)),
                ('videp_link', models.CharField(help_text='youtube video link', max_length=200, null=True)),
                ('date', models.DateField()),
            ],
        ),
    ]
