# Generated by Django 3.0.8 on 2021-06-23 14:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('stepcell', '0002_youtubeupdate'),
    ]

    operations = [
        migrations.RenameField(
            model_name='youtubeupdate',
            old_name='videp_link',
            new_name='video_link',
        ),
    ]
