# Generated by Django 3.0.8 on 2021-06-23 16:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stepcell', '0003_auto_20210623_1934'),
    ]

    operations = [
        migrations.CreateModel(
            name='OngoingEvent',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('event_name', models.CharField(max_length=200, null=True)),
                ('image', models.ImageField(upload_to='ongoingEvent/')),
            ],
        ),
    ]
