# Generated by Django 3.0.8 on 2021-06-23 17:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stepcell', '0004_ongoingevent'),
    ]

    operations = [
        migrations.AddField(
            model_name='ongoingevent',
            name='event_link',
            field=models.URLField(help_text='registration page link for the event', max_length=300, null=True),
        ),
    ]
