# Generated by Django 3.0.8 on 2021-06-23 17:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('stepcell', '0005_ongoingevent_event_link'),
    ]

    operations = [
        migrations.RenameField(
            model_name='ongoingevent',
            old_name='image',
            new_name='event_poster',
        ),
    ]
