# Generated by Django 3.0.8 on 2021-06-24 08:48

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stepcell', '0006_auto_20210623_2234'),
    ]

    operations = [
        migrations.CreateModel(
            name='Coordinator',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(help_text='student name', max_length=100)),
                ('branch', models.CharField(help_text='branch', max_length=300)),
                ('phone', models.CharField(default='', help_text='10 digits number', max_length=50)),
                ('linkedin_link', models.CharField(help_text='linkedin profile link', max_length=300)),
                ('insta_link', models.CharField(help_text='instagram profile link', max_length=300)),
                ('profile_image', models.FileField(upload_to='', validators=[django.core.validators.FileExtensionValidator(['jpg', 'png', 'jpeg'])])),
            ],
        ),
        migrations.CreateModel(
            name='VeteranCoordinator',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(help_text='student name', max_length=100)),
                ('branch', models.CharField(help_text='branch', max_length=300)),
                ('phone', models.CharField(default='', help_text='10 digits number', max_length=50)),
                ('linkedin_link', models.CharField(help_text='linkedin profile link', max_length=300)),
                ('insta_link', models.CharField(help_text='instagram profile link', max_length=300)),
                ('profile_image', models.FileField(upload_to='', validators=[django.core.validators.FileExtensionValidator(['jpg', 'png', 'jpeg'])])),
            ],
        ),
    ]
