# Generated by Django 3.0.8 on 2021-06-24 08:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stepcell', '0007_coordinator_veterancoordinator'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coordinator',
            name='insta_link',
            field=models.CharField(default='#', help_text='instagram profile link', max_length=300),
        ),
        migrations.AlterField(
            model_name='coordinator',
            name='linkedin_link',
            field=models.CharField(default='#', help_text='linkedin profile link', max_length=300),
        ),
        migrations.AlterField(
            model_name='coordinator',
            name='phone',
            field=models.IntegerField(help_text='!0-digits number'),
        ),
        migrations.AlterField(
            model_name='veterancoordinator',
            name='insta_link',
            field=models.CharField(default='#', help_text='instagram profile link', max_length=300),
        ),
        migrations.AlterField(
            model_name='veterancoordinator',
            name='linkedin_link',
            field=models.CharField(default='#', help_text='linkedin profile link', max_length=300),
        ),
        migrations.AlterField(
            model_name='veterancoordinator',
            name='phone',
            field=models.IntegerField(help_text='!0-digits number'),
        ),
    ]
