# Generated by Django 3.0.8 on 2021-06-24 13:04

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stepcell', '0008_auto_20210624_1420'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coordinator',
            name='profile_image',
            field=models.FileField(upload_to='coordinators/', validators=[django.core.validators.FileExtensionValidator(['jpg', 'png', 'jpeg'])]),
        ),
        migrations.AlterField(
            model_name='veterancoordinator',
            name='profile_image',
            field=models.FileField(upload_to='veteranCoordinators/', validators=[django.core.validators.FileExtensionValidator(['jpg', 'png', 'jpeg'])]),
        ),
    ]
