# Generated by Django 3.0.8 on 2021-06-26 14:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stepcell', '0009_auto_20210624_1834'),
    ]

    operations = [
        migrations.CreateModel(
            name='AbhivyaktiEvent',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('event_name', models.CharField(max_length=200, null=True)),
                ('event_poster', models.ImageField(help_text='your image should be in size ratio 3:2', upload_to='ongoingEvent/')),
                ('event_link', models.URLField(help_text='registration page link for the event', max_length=300, null=True)),
            ],
        ),
    ]
