# Generated by Django 3.0.8 on 2021-06-28 13:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stepcell', '0010_abhivyaktievent'),
    ]

    operations = [
        migrations.AddField(
            model_name='abhivyaktievent',
            name='event_desc',
            field=models.CharField(help_text='about event', max_length=400, null=True),
        ),
    ]
