# Generated by Django 3.0.8 on 2021-06-28 17:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stepcell', '0011_abhivyaktievent_event_desc'),
    ]

    operations = [
        migrations.AlterField(
            model_name='abhivyaktievent',
            name='event_poster',
            field=models.ImageField(help_text='your image should be in size ratio 3:2', upload_to='abhivyaktiEvent/'),
        ),
    ]
