# Generated by Django 3.0.8 on 2021-06-28 17:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stepcell', '0012_auto_20210628_2310'),
    ]

    operations = [
        migrations.AlterField(
            model_name='abhivyaktievent',
            name='event_link',
            field=models.URLField(default='#', help_text='registration page link for the event', max_length=300, null=True),
        ),
    ]
