# Generated by Django 3.0.8 on 2021-06-28 18:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stepcell', '0014_auto_20210628_2314'),
    ]

    operations = [
        migrations.CreateModel(
            name='AbhivyaktiPerformingEvent',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('event_name', models.CharField(max_length=200, null=True)),
                ('event_desc', models.CharField(help_text='about event', max_length=1000, null=True)),
                ('event_poster', models.ImageField(help_text='your image should be in size ratio 3:2', upload_to='abhivyaktiEvent/')),
            ],
        ),
    ]
