# Generated by Django 3.0.8 on 2021-07-01 17:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stepcell', '0019_controlveteran'),
    ]

    operations = [
        migrations.AddField(
            model_name='team',
            name='linkedin_link',
            field=models.CharField(default='#', help_text='linkedin profile link', max_length=300),
        ),
    ]
