# Generated by Django 3.0.8 on 2021-07-01 17:59

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stepcell', '0022_auto_20210701_2318'),
    ]

    operations = [
        migrations.CreateModel(
            name='Gallery',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('event', models.CharField(help_text='event', max_length=300)),
                ('image', models.FileField(upload_to='gallery/', validators=[django.core.validators.FileExtensionValidator(['jpg', 'png'])])),
            ],
        ),
    ]
