# Generated by Django 3.0.8 on 2021-07-03 14:23

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stepcell', '0024_auto_20210701_2331'),
    ]

    operations = [
        migrations.CreateModel(
            name='OngoingEventCarousel',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(help_text='name of the event', max_length=50, null=True)),
                ('class_name', models.CharField(default='not active', help_text='active class or not', max_length=50)),
                ('image', models.FileField(upload_to='coordinators/', validators=[django.core.validators.FileExtensionValidator(['jpg', 'png', 'jpeg'])])),
            ],
        ),
    ]
