# Generated by Django 3.0.8 on 2021-07-03 17:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stepcell', '0025_ongoingeventcarousel'),
    ]

    operations = [
        migrations.CreateModel(
            name='OngoingEventRegisteration',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(blank=True, max_length=100)),
                ('email', models.EmailField(blank=True, max_length=300)),
                ('phone', models.IntegerField(blank=True)),
                ('college', models.CharField(blank=True, max_length=300)),
                ('field1', models.CharField(blank=True, max_length=200)),
                ('field2', models.CharField(blank=True, max_length=200)),
                ('field3', models.CharField(blank=True, max_length=200)),
            ],
        ),
    ]
