# Generated by Django 3.0.8 on 2021-07-04 06:52

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stepcell', '0026_ongoingeventregisteration'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ongoingeventcarousel',
            name='image',
            field=models.FileField(upload_to='ongoingEventCarousel/', validators=[django.core.validators.FileExtensionValidator(['jpg', 'png', 'jpeg'])]),
        ),
    ]
