# Generated by Django 3.0.8 on 2021-07-04 07:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stepcell', '0027_auto_20210704_1222'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coordinator',
            name='phone',
            field=models.CharField(blank=True, help_text='10-digits number', max_length=12),
        ),
        migrations.AlterField(
            model_name='team',
            name='phone',
            field=models.CharField(blank=True, help_text='10 digits phone number', max_length=12),
        ),
        migrations.AlterField(
            model_name='veterancoordinator',
            name='phone',
            field=models.CharField(blank=True, help_text='10-digits number', max_length=12),
        ),
    ]
