# Generated by Django 3.0.8 on 2021-07-04 13:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stepcell', '0028_auto_20210704_1232'),
    ]

    operations = [
        migrations.AddField(
            model_name='ongoingevent',
            name='event_registeration_date',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
