# Generated by Django 3.0.8 on 2021-07-04 13:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stepcell', '0029_ongoingevent_event_registeration_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ongoingevent',
            name='event_registeration_date',
            field=models.DateField(),
        ),
    ]
