# Generated by Django 3.0.8 on 2021-07-04 14:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stepcell', '0030_auto_20210704_1841'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ongoingevent',
            name='event_link',
            field=models.CharField(help_text='registration page link for the event', max_length=300, null=True),
        ),
    ]
